services:
    rabbitmq:
        image: rabbitmq:4.0.2-management-alpine
        container_name: rabbitmq
        ports:
            - "5672:5672" # Default port for RabbitMQ
            - "15672:15672" # Default port for RabbitMQ Management Plugin
        environment:
            RABBITMQ_DEFAULT_USER: rabbitmq_user
            RABBITMQ_DEFAULT_PASS: rabbitmq_123456
        volumes:
            - ./rabbitMQ/rabbitmq_data:/var/lib/rabbitmq/mnesia
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 4G
                reservations:
                    cpus: "1"
                    memory: 2G
        networks:
            - my-network

    order:
        image: order
        container_name: order
        build:
            context: ./order
            dockerfile: Dockerfile
        ports:
            - "8081:8081"
        depends_on:
            - rabbitmq
        environment:
            - SPRING_RABBITMQ_HOST=rabbitmq
            - SPRING_RABBITMQ_PORT=5672
            - SPRING_RABBITMQ_USERNAME=rabbitmq_user
            - SPRING_RABBITMQ_PASSWORD=rabbitmq_123456
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 2G
                reservations:
                    cpus: "0.5"
                    memory: 1G
        networks:
            - my-network

    orchestration:
        image: orchestration
        container_name: orchestration
        build:
            context: ./orchestration
            dockerfile: Dockerfile
        ports:
            - "8082:8082"
        depends_on:
            - rabbitmq
        environment:
            - SPRING_RABBITMQ_HOST=rabbitmq
            - SPRING_RABBITMQ_PORT=5672
            - SPRING_RABBITMQ_USERNAME=rabbitmq_user
            - SPRING_RABBITMQ_PASSWORD=rabbitmq_123456
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 2G
                reservations:
                    cpus: "0.5"
                    memory: 1G
        networks:
            - my-network

    payment:
        image: payment
        container_name: payment
        build:
            context: ./payment
            dockerfile: Dockerfile
        ports:
            - "8083:8083"
        depends_on:
            - rabbitmq
        environment:
            - SPRING_RABBITMQ_HOST=rabbitmq
            - SPRING_RABBITMQ_PORT=5672
            - SPRING_RABBITMQ_USERNAME=rabbitmq_user
            - SPRING_RABBITMQ_PASSWORD=rabbitmq_123456
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 2G
                reservations:
                    cpus: "0.5"
                    memory: 1G
        networks:
            - my-network

    inventory:
        image: inventory
        container_name: inventory
        build:
            context: ./inventory
            dockerfile: Dockerfile
        ports:
            - "8084:8084"
        depends_on:
            - rabbitmq
        environment:
            - SPRING_RABBITMQ_HOST=rabbitmq
            - SPRING_RABBITMQ_PORT=5672
            - SPRING_RABBITMQ_USERNAME=rabbitmq_user
            - SPRING_RABBITMQ_PASSWORD=rabbitmq_123456
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 2G
                reservations:
                    cpus: "0.5"
                    memory: 1G
        networks:
            - my-network

    shipping:
        image: shipping
        container_name: shipping
        build:
            context: ./shipping
            dockerfile: Dockerfile
        ports:
            - "8085:8085"
        depends_on:
            - rabbitmq
        environment:
            - SPRING_RABBITMQ_HOST=rabbitmq
            - SPRING_RABBITMQ_PORT=5672
            - SPRING_RABBITMQ_USERNAME=rabbitmq_user
            - SPRING_RABBITMQ_PASSWORD=rabbitmq_123456
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 2G
                reservations:
                    cpus: "0.5"
                    memory: 1G
        networks:
            - my-network

    notification:
        image: notification
        container_name: notification
        build:
            context: ./notification
            dockerfile: Dockerfile
        ports:
            - "8086:8086"
        depends_on:
            - rabbitmq
        environment:
            - SPRING_RABBITMQ_HOST=rabbitmq
            - SPRING_RABBITMQ_PORT=5672
            - SPRING_RABBITMQ_USERNAME=rabbitmq_user
            - SPRING_RABBITMQ_PASSWORD=rabbitmq_123456
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 2G
                reservations:
                    cpus: "0.5"
                    memory: 1G
        networks:
            - my-network

networks:
    my-network:
