server:
  port: 8086

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

notification:
  queue:
    orderCreated: orderCreatedNotificationQueue
    paymentProcessed: paymentProcessedNotificationQueue
    inventoryUpdated: inventoryUpdatedNotificationQueue
    orderShipped: orderShippedNotificationQueue
  exchange: notificationExchange

logging:
  level:
    org:
      springframework: INFO
    com:
      e_commerce: DEBUG
