server:
  port: 8086

spring:
  application:
    name:  notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 100
        concurrency: 100
        max-concurrency: 200

notification:
  queue:
    orderCreated: orderCreatedNotificationQueue
    paymentProcessed: paymentProcessedNotificationQueue
    inventoryUpdated: inventoryUpdatedNotificationQueue
    orderShipped: orderShippedNotificationQueue
  exchange: notificationExchange

logging:
  level:
    org:
      springframework: INFO
    com:
      e_commerce: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"