server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

orchestration:
  exchange: orchestrationExchange

logging:
  level:
    org:
      springframework: INFO
    com:
      e_commerce: DEBUG
