server:
  port: 8084

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

inventory:
  queue:
    updateRequested: inventoryUpdateRequestedQueue

orchestration:
  exchange: orchestrationExchange

logging:
  level:
    org:
      springframework: INFO
    com:
      e_commerce: DEBUG
