server:
  port: 8084

spring:
  application:
    name:  inventory-service
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq_user
    password: rabbitmq_123456
    listener:
      simple:
        prefetch: 100
        concurrency: 100
        max-concurrency: 200

inventory:
  queue:
    updateRequested: inventoryUpdateRequestedQueue

orchestration:
  exchange: orchestrationExchange

logging:
  level:
    org:
      springframework: INFO
    com:
      e_commerce: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
