server:
  port: 8086

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: password

shipping:
  queue:
    requested: shippingRequestedQueue

orchestration:
  exchange: orchestrationExchange

logging:
  level:
    org:
      springframework: INFO
    com:
      e_commerce: DEBUG
