server:
  port: 8085

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

shipping:
  queue:
    requested: shippingRequestedQueue

orchestration:
  exchange: orchestrationExchange

logging:
  level:
    org:
      springframework: INFO
    com:
      e_commerce: DEBUG
