server:
  port: 8084

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: password

payment:
  queue:
    requested: paymentRequestedQueue

orchestration:
  exchange: orchestrationExchange

logging:
  level:
    org:
      springframework: INFO
    com:
      e_commerce: DEBUG
