server:
  port: 8083

spring:
  application:
    name:  payment-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 100
        concurrency: 100
        max-concurrency: 200

payment:
  queue:
    requested: paymentRequestedQueue

orchestration:
  exchange: orchestrationExchange

logging:
  level:
    org:
      springframework: INFO
    com:
      e_commerce: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"