server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

payment:
  queue:
    requested: paymentRequestedQueue

orchestration:
  exchange: orchestrationExchange

logging:
  level:
    org:
      springframework: INFO
    com:
      e_commerce: DEBUG
