server:
  port: 8082

spring:
  application:
    name: orchestration-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 100
        concurrency: 100
        max-concurrency: 200

orchestration:
  queue:
    orderCreated: orderCreatedQueue
    paymentProcessed: paymentProcessedQueue
    inventoryUpdated: inventoryUpdatedQueue
    orderShipped: orderShippedQueue
  exchange: orchestrationExchange

notification:
  exchange: notificationExchange

logging:
  level:
    org.springframework: INFO
    com.e_commerce: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
